# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True)),
                ('genre', models.CharField(max_length=128)),
                ('youtube', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('soundcloud', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('info', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='images/artists/')),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(blank=True, max_length=128)),
                ('bookings', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glasgowgigs.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('bookings', models.ManyToManyField(blank=True, to='glasgowgigs.Event')),
                ('favourite_artists', models.ManyToManyField(blank=True, to='glasgowgigs.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('address', models.CharField(max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='images/venues/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favourite_venues',
            field=models.ManyToManyField(blank=True, to='glasgowgigs.Venue'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glasgowgigs.Venue'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('venue', 'artist', 'date')]),
        ),
    ]
