# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasgowgigs', '0002_auto_20180322_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
    ]
