# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasgowgigs', '0003_remove_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bookings',
            field=models.ManyToManyField(to='glasgowgigs.Event'),
        ),
    ]
