# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasgowgigs', '0005_auto_20180327_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='favourite_artists',
            new_name='favartists',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='favourite_venues',
            new_name='favvenues',
        ),
    ]
