# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasgowgigs', '0007_auto_20180309_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=128, unique_for_date='date'),
        ),
    ]
