# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glasgowgigs', '0009_auto_20180309_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('bookings', models.ManyToManyField(to='glasgowgigs.Event')),
                ('favourite_artists', models.ManyToManyField(to='glasgowgigs.Artist')),
                ('favourite_venues', models.ManyToManyField(to='glasgowgigs.Venue')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
