# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasgowgigs', '0018_auto_20180310_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=128),
        ),
    ]
