# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasgowgigs', '0020_auto_20180310_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
    ]
