# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasgowgigs', '0025_remove_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
