# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasgowgigs', '0026_artist_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='soundcloud',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
