# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasgowgigs', '0028_artist_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
