# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasgowgigs', '0029_artist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/venues/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/artists/'),
        ),
    ]
