# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasgowgigs', '0030_auto_20180310_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
