# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasgowgigs', '0031_auto_20180313_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bookings',
            field=models.ManyToManyField(blank=True, to='glasgowgigs.Event'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_artists',
            field=models.ManyToManyField(blank=True, to='glasgowgigs.Artist'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_venues',
            field=models.ManyToManyField(blank=True, to='glasgowgigs.Venue'),
        ),
    ]
