# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 16:04
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('glasgowgigs', '0036_auto_20180321_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
