from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Artist(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(blank=True)


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Artist, self).save(*args, **kwargs)

    def __str__(self): # For Python 2, use __unicode__ too
        return self.name


class Venue(models.Model):
    name = models.CharField(max_length=128, unique=True)
    address = models.CharField(max_length=128, unique=True) 
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(blank=True)
    #no need for theslug to be unique as it is
    #generated by artist name + venue name which are guaranteed to be unique

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Venue, self).save(*args, **kwargs)

    def __str__(self): # For Python 2, use __unicode__ too
        return self.name

class Event(models.Model):
    name = models.CharField(max_length=128, blank=True)
    venue = models.ForeignKey(Venue)
    artist = models.ForeignKey(Artist)
    date = models.DateField()
    bookings = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(blank=True)

    def __str__(self): # For Python 2, use __unicode__ too
        return self.name
    def save (self, *args, **kwargs):
        if self.venue and self.artist:
            self.name = self.artist.name+" @ "+self.venue.name
        self.slug = slugify(self.name)
        super(Event, self).save(*args, **kwargs)
